theme:
title: This is Kyle
description: Kyle Sherman's Writing
show_downloads: false
tag_page_dir: tags
permalink: /posts/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
twitter:
  username: drumnkyle
